version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
  queue-manager:
    image: redis:latest # Assuming Redis is used for queueing with Bull
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
